// Generated by CoffeeScript 1.8.0
(function() {
  var async, cheerio, fs, ninghao, request, test;

  request = require("request");

  async = require("async");

  fs = require("fs");

  cheerio = require("cheerio");

  ninghao = function(cookie, url) {
    this.cookie = cookie;
    this.url = url;
    this.href = [];
    this.info = {};
  };

  ninghao.prototype.reqOp = function(url) {
    var options;
    options = {
      url: url,
      headers: {
        'User-Agent': 'request',
        'Cookie': this.cookie
      }
    };
    return options;
  };

  ninghao.prototype.getUrl = function() {

    /* 获取课程列表 */
    var op, self;
    self = this;
    op = self.reqOp(self.url);
    return request.get(op, function(err, res, body) {
      var $, link, linkLen;
      if (err) {
        return console.log("获取课程页面失败，检查网络");
      }
      $ = cheerio.load(body);
      link = $("tr > td a");
      linkLen = link.length;
      console.log("查找到得课程列表： " + linkLen);
      if (!linkLen) {
        console.log("奇怪怎么没有找到课程列表？");
        return false;
      }
      link.each(function(idx, element) {
        return self.href.push($(element).attr("href"));
      });
      if (!self.href.length) {
        console.log("奇怪，应该不会出现这情况吧, @href 为空？");
        return false;
      }
      console.log("### 获取课程列表 end ###");
      return self.doTask();
    });
  };

  ninghao.prototype.doTask = function() {

    /* 去获取课程详情页面的下载链接信息 */
    var self;
    self = this;
    return async.eachSeries(self.href, function(item, callback) {
      var url;
      url = 'http://ninghao.net' + item;
      return self.getDownInfo(url, callback);
    }, function(eachErr) {
      if (eachErr) {
        console.log('oo)oo(oo');
        return console.log(eachErr);
      }
      return console.log("all do");
    });
  };

  ninghao.prototype.getDownInfo = function(url, cb) {
    var op, self;
    self = this;
    op = self.reqOp(url);
    return request.get(op, function(err, res, body) {
      var $, findElent;
      if (err) {
        console.log(err);
        console.log("获取下载链接出错，准备3s后重试。。。");
        return setTimeout(function() {
          return self.getDownInfo(url, cb);
        }, 3000);
      }
      $ = cheerio.load(body);
      findElent = $("#sidebar section div.box");
      self.info.url = $('script:contains("这不是秘密哦")').text().trim().split("\n")[2].split('"')[1];
      self.info.name = findElent.eq(0).find("strong").find("a").text();
      if (!self.info.url || !self.info.name) {
        return console.log("没有发现下载的课程名和URL");
      }
      console.log("获取到 " + self.info.name + " 以及下载URL " + self.info.url);
      return self.downVideo(cb);
    });
  };

  ninghao.prototype.downVideo = function(cb) {
    var op, self, write;
    self = this;
    op = self.reqOp(self.info.url);
    write = fs.createWriteStream(self.info.name + ".mp4");
    return request.get(op).on('response', function(res) {
      console.log(".................................");
      console.log("" + self.info.name + "  " + self.info.url);
      console.log(res.statusCode);
      if (res.statusCode === 200) {
        return console.log('连接下载视频成功');
      }
    }).on("error", function(err) {
      console.log("" + self.info.name + "  " + self.info.url + " down error: " + err);
      console.log("下载视频出错，准备3s后重试。。。");
      return setTimeout(function() {
        return self.downVideo(url, cb);
      }, 3000);
    }).on('end', function() {
      console.log("" + self.info.name + " 下载成功");
      return cb();
    }).pipe(write);
  };

  test = new ninghao('123', 'http://ninghao.net/course/2034');

  test.getUrl();

}).call(this);

//# sourceMappingURL=app.js.map
