// Generated by CoffeeScript 1.10.0
(function() {
  var NingHao, async, cheerio, fs, ng, request;

  request = require('request');

  async = require("async");

  fs = require("fs");

  cheerio = require('cheerio');

  NingHao = (function() {
    function NingHao(courseUrl) {
      this.courseUrl = courseUrl;
      this.courseName = 'ninghao';
      this.hrefList = [];
    }

    NingHao.prototype.getRepOP = function(url) {
      var options;
      options = {
        url: url,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36',
          'Cookie': ''
        }
      };
      return options;
    };

    NingHao.prototype.getUrl = function(cb) {
      var _this, op;
      _this = this;
      op = _this.getRepOP(_this.courseUrl);
      return request.get(op, function(err, res, body) {
        var $, urlList;
        if (err) {
          return cb(err);
        }
        $ = cheerio.load(body);
        urlList = $("div.header > a");
        if (urlList.length === 0) {
          return cb("没有找到课程列表");
        }
        urlList.each(function(idx, ele) {
          var name, tmp, url;
          url = $(ele).attr('href');
          name = $(ele).text();
          if (url.indexOf('video') > 0) {
            tmp = {
              url: 'http://ninghao.net' + url,
              name: name
            };
            return _this.hrefList.push(tmp);
          }
        });
        return cb();
      });
    };

    NingHao.prototype.getSource = function(cb) {
      var _this;
      _this = this;
      console.log(_this.hrefList);
      return async.each(_this.hrefList, function(item, callback) {
        var name, op, url;
        url = item['url'];
        name = item['name'];
        op = _this.getRepOP(url);
        return request.get(op, function(err, res, body) {
          var $, source;
          if (err) {
            return cb(err);
          }
          $ = cheerio.load(body);
          source = $("source");
          if (source.length === 0) {
            console.log("Url没有视频", url, name);
            return callback();
          }
          item['video'] = source.attr('src');
          console.log(item);
          return callback();
        });
      }, function(err) {
        if (err) {
          return console.log(err);
        }
        console.log(_this.hrefList);
        return cb();
      });
    };

    NingHao.prototype.downInfo = function(cb) {
      var _this;
      _this = this;
      return async.eachSeries(_this.hrefList, function(item, callback) {
        return _this.downVideo(item.video, item.name, callback);
      }, function(err) {
        console.log(err);
        return cb();
      });
    };

    NingHao.prototype.downVideo = function(url, name, cb) {
      var _this, op, write;
      _this = this;
      write = fs.createWriteStream(name + ".mp4");
      if (!url) {
        return cb();
      }
      op = _this.getRepOP(url);
      return request.get(op).on('response', function(res) {
        console.log(".................................");
        console.log(name + "  " + url);
        console.log(res.statusCode);
        if (res.statusCode === 200) {
          return console.log('连接下载视频成功');
        }
      }).on("error", function(err) {
        console.log(name + "  " + url + " down error: " + err);
        console.log("下载视频出错，准备3s后重试。。。");
        return setTimeout(function() {
          return self.downVideo(url, name, cb);
        }, 3000);
      }).on('end', function() {
        console.log(name + " 下载成功");
        console.log(".................................\n\n\n\n");
        return cb();
      }).pipe(write);
    };

    return NingHao;

  })();

  ng = new NingHao('http://ninghao.net/course/3032');

  async.waterfall([
    function(cb) {
      return ng.getUrl(cb);
    }, function(cb) {
      return ng.getSource(cb);
    }, function(cb) {
      return ng.downInfo(cb);
    }
  ]);

}).call(this);

//# sourceMappingURL=new_app.js.map
