// Generated by CoffeeScript 1.8.0
(function() {
  var fs;

  fs = require('fs');

  fs.mkdirSync('MySQL 基础教程2');

  fs.createWriteStream('MySQL 基础教程/a.txt');

}).call(this);

//# sourceMappingURL=test.js.map
