// Generated by CoffeeScript 1.8.0
(function() {
  var a, async, cheerio, fs, log, op, reqOp, request;

  request = require("request");

  async = require("async");

  fs = require("fs");

  cheerio = require("cheerio");

  reqOp = function(url) {
    var options;
    options = {
      url: url,
      headers: {
        'User-Agent': 'request',
        'Cookie': ''
      }
    };
    return options;
  };

  op = reqOp("http://ninghao.net/files/styles/cover/public/poster/git-cd.jpg?itok=5l4Q7fp6");

  request.get(op, function(err, res, body) {
    if (err) {
      return console.log("err");
    }
    fs.writeFile('out.jpg', body, 'binary');
    return console.log("ok");
  }).pipe(fs.createWriteStream('a11123.jpg'));

  a = fs.createWriteStream("err.log");

  log = function(data) {
    console.log(data);
    return a.write(data);
  };

}).call(this);

//# sourceMappingURL=test.js.map
